# Generated by Django 4.1.3 on 2022-11-22 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0002_auto_20221120_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.mentor'),
        ),
        migrations.AlterField(
            model_name='week',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.course'),
        ),
        migrations.AlterField(
            model_name='weekstatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.student'),
        ),
        migrations.AlterField(
            model_name='weekstatus',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.week'),
        ),
    ]
