# Generated by Django 4.1.3 on 2023-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0003_weekstatus_file_weekstatus_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="lab_manual",
            field=models.FileField(blank=True, null=True, upload_to="lab_manuals/"),
        ),
    ]
