# Generated by Django 4.1.1 on 2022-11-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_degree_rename_lab_code_course_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_name',
        ),
    ]
