# Generated by Django 4.1.3 on 2022-11-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_course_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course'),
        ),
        migrations.AlterField(
            model_name='week',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course'),
        ),
        migrations.AlterField(
            model_name='weekstatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.student'),
        ),
        migrations.AlterField(
            model_name='weekstatus',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.week'),
        ),
    ]
