# Generated by Django 4.1.3 on 2022-11-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_student_course_alter_week_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='image',
        ),
    ]
